<a href="https://colab.research.google.com/github/wilbertcaine/COMP4211/blob/main/Project/Project.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [77]:
# https://drive.google.com/file/d/199mVXHt5cxT68gBXCcucMjtJzCwvc8ud/view?usp=sharing
# https://drive.google.com/file/d/1d2hJyvo2Go4FxK7br0exFQFdZ1eCexIA/view?usp=sharing
# https://drive.google.com/file/d/1yjsMICWqHdEUhF758ndq0hLO96FrYWkR/view?usp=sharing
%cd /content
!mkdir -p dataset
%cd /content/dataset
!gdown --id 199mVXHt5cxT68gBXCcucMjtJzCwvc8ud
!gdown --id 1d2hJyvo2Go4FxK7br0exFQFdZ1eCexIA
!gdown --id 1yjsMICWqHdEUhF758ndq0hLO96FrYWkR

# https://drive.google.com/file/d/1p1NQBepQeY-b1hXe9RJVZ3Rrx6-u_UPJ/view?usp=sharing
# https://drive.google.com/file/d/1vYIcELaxAVF2tXX03XK9m4k2727vufvw/view?usp=sharing
# !gdown --id 1p1NQBepQeY-b1hXe9RJVZ3Rrx6-u_UPJ
# !gdown --id 1vYIcELaxAVF2tXX03XK9m4k2727vufvw

%cd ../

/content
/content/dataset
Downloading...
From: https://drive.google.com/uc?id=199mVXHt5cxT68gBXCcucMjtJzCwvc8ud
To: /content/dataset/train.csv
100% 7.62M/7.62M [00:00<00:00, 24.2MB/s]
Downloading...
From: https://drive.google.com/uc?id=1d2hJyvo2Go4FxK7br0exFQFdZ1eCexIA
To: /content/dataset/Test_Jan.csv
100% 124k/124k [00:00<00:00, 3.91MB/s]
Downloading...
From: https://drive.google.com/uc?id=1yjsMICWqHdEUhF758ndq0hLO96FrYWkR
To: /content/dataset/Predict_Jan.csv
100% 20.7k/20.7k [00:00<00:00, 6.05MB/s]
Downloading...
From: https://drive.google.com/uc?id=1p1NQBepQeY-b1hXe9RJVZ3Rrx6-u_UPJ
To: /content/dataset/video59-tool.txt
100% 20.5k/20.5k [00:00<00:00, 5.43MB/s]
Downloading...
From: https://drive.google.com/uc?id=1vYIcELaxAVF2tXX03XK9m4k2727vufvw
To: /content/dataset/video78-phase.txt
100% 495k/495k [00:00<00:00, 7.71MB/s]
/content


# Trash

In [76]:
df = np.loadtxt(f'dataset/video{str(59).zfill(2)}-tool.txt', skiprows=1)
# df = np.delete(df, 0, axis=1)
df

array([[0.0000e+00, 0.0000e+00, 0.0000e+00, ..., 0.0000e+00, 0.0000e+00,
        0.0000e+00],
       [2.5000e+01, 0.0000e+00, 0.0000e+00, ..., 0.0000e+00, 0.0000e+00,
        0.0000e+00],
       [5.0000e+01, 0.0000e+00, 0.0000e+00, ..., 0.0000e+00, 0.0000e+00,
        0.0000e+00],
       ...,
       [2.6075e+04, 1.0000e+00, 0.0000e+00, ..., 0.0000e+00, 0.0000e+00,
        1.0000e+00],
       [2.6100e+04, 1.0000e+00, 0.0000e+00, ..., 0.0000e+00, 0.0000e+00,
        1.0000e+00],
       [2.6125e+04, 1.0000e+00, 0.0000e+00, ..., 0.0000e+00, 0.0000e+00,
        1.0000e+00]])

In [ ]:
full_phase = np.array(['Preparation', 'CalotTriangleDissection', 'ClippingCutting', 'GallbladderDissection', 'GallbladderPackaging', 'CleaningCoagulation', 'GallbladderRetraction'])
full_phase = np.expand_dims(full_phase, axis=1)
for i in range(1,80):
    df = np.loadtxt(f'dataset/Cholec80/phase_annotations/video{str(i).zfill(2)}-phase.txt', dtype=str, skiprows=1)
    df = np.delete(df, 0, axis=1)
    df = np.concatenate((full_phase, df))
    df = df.flatten()
    df = pd.get_dummies(df)
    df = np.array(df)
    df = np.delete(df, range(0,7), axis=0)
    if df.shape[1] != 7:
        print(df.shape[1]) 



In [61]:
np.expand_dims(full_phase, axis=1)

array([['Preparation'],
       ['CalotTriangleDissection'],
       ['ClippingCutting'],
       ['GallbladderDissection'],
       ['GallbladderPackaging'],
       ['CleaningCoagulation'],
       ['GallbladderRetraction']], dtype='<U23')

In [70]:
full_phase = np.array(['Preparation', 'CalotTriangleDissection', 'ClippingCutting', 'GallbladderDissection', 'GallbladderPackaging', 'CleaningCoagulation', 'GallbladderRetraction'])
full_phase = np.expand_dims(full_phase, axis=1)
df = np.loadtxt(f'dataset/video{str(78).zfill(2)}-phase.txt', dtype=str, skiprows=1)
df = np.delete(df, 0, axis=1)
df = np.concatenate((full_phase, df))
df = df.flatten()
df = pd.get_dummies(df)
df = np.array(df)
df = np.delete(df, range(0,7), axis=0)

[[0 0 0 ... 0 0 1]
 [0 0 0 ... 0 0 1]
 [0 0 0 ... 0 0 1]
 ...
 [0 0 0 ... 0 1 0]
 [0 0 0 ... 0 1 0]
 [0 0 0 ... 0 1 0]]


# Data

In [115]:
df = pd.read_csv('dataset/train.csv')
df = df.drop(columns="datetime")
# df['datetime']=pd.to_datetime(df['datetime'])
# df['week_day']=df['datetime'].dt.dayofweek
# df['date']=df['datetime'].dt.day
# df['month']=df['datetime'].dt.month
# df['hour']=df['datetime'].dt.hour
a, b, c = np.split(df, [int(.7*len(df)), int(.85*len(df))])

In [127]:
len(a)

30642

# Model

In [ ]:
import os
import pandas as pd
import numpy as np
from torch.utils.data import Dataset
from torch.utils.data import DataLoader

In [135]:
class FC_Net_Dataset(Dataset):
    def __init__(self, split, csv_dir='dataset/train.csv'):
        """
        Keyword arguments:
        split -- an integer either 0, 1, or 2 which indicates train, validation, or test
        """
        super(FC_Net_Dataset, self).__init__()
        df = pd.read_csv(csv_dir)
        df = df.drop(columns="datetime")
        data = np.split(df, [int(.7*len(df)), int(.85*len(df))])
        self.data = np.array(data[split])

    def __getitem__(self, idx):
        return self.data[idx][1:], self.data[idx][0]

    def __len__(self):
        return len(self.data)

In [141]:
import os
import numpy as np
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim
from torch.utils.data import Dataset

In [142]:
class FC_Net(nn.Module):
    def __init__(self):
        super(FC_Net, self).__init__()

        self.fc1 = nn.Linear(15, 64)
        self.fc2 = nn.Linear(64, 64)
        self.fc3 = nn.Linear(64, 8)
        self.fc4 = nn.Linear(8, 1)
        self.relu = nn.ReLU(inplace=True)
        self.bn = nn.BatchNorm1d(100, affine=False)
 
    def forward(self, x):
        x = self.fc1(x)
        x = self.relu(x)

        x = self.fc2(x)
        x = self.relu(x)

        x = self.fc3(x)
        x = self.relu(x)
        x = self.bn(x)

        x = self.fc4(x)
        x = self.bn(x)
        x = self.relu(x)
        return x

In [ ]:
def train_epoch(net, optimizer, loss_fn, dataloader, epoch, writer=None, device='cpu'):
    ep_loss = 0.0
    num_iter = len(dataloader)
    net.train()
    grad_max = 100.
    for n_iter, (xs, y) in enumerate(tqdm(dataloader)):
        curr_iter = epoch * num_iter + n_iter
        xs, y = xs.to(device), y.to(device)
        pred = net(xs) ## step 1. get output
        loss = loss_fn(pred, y) ## step 2. compute loss
        optimizer.zero_grad()
        loss.backward() ## step 3. backpropagation
        nn.utils.clip_grad_norm_(net.parameters(), grad_max) ## L2-norm gradient clipping
        optimizer.step() ## step 4. update model weigth
        if writer is not None:
            writer.add_scalar('Loss/train', loss.data, curr_iter)
        # print("\n[ITER %d] LOSS: %.4f" % (curr_iter, loss.data))
        ep_loss += loss.data
    ep_loss /= len(dataloader)
    if writer is not None:
        writer.add_scalar('EpLoss/train', ep_loss, epoch)
    print("\n[EP %d] Train LOSS: %.4f" % (epoch, ep_loss))
    return ep_loss

@torch.no_grad()
def val_epoch(net, loss_fn, dataloader, epoch, val_set, writer=None, device='cpu'):
    ep_loss = 0.0
    net.eval()
    preds, ys = [], []
    for n_iter, (xs, y) in enumerate(tqdm(dataloader)):
        xs, y = xs.to(device), y.to(device)
        pred = net(xs)
        loss = loss_fn(pred, y)
        ep_loss += loss.data
        preds.append(pred.squeeze())
        ys.append(y)
    ep_loss /= len(dataloader)
    print("\n[EP %d] Val LOSS: %.4f" % (epoch, ep_loss))

    preds = torch.stack(preds).squeeze()
    ys = torch.stack(ys).squeeze()
    # if (epoch + 1) % 5 == 0:
    ## denormalize
    preds = preds * val_set.std + val_set.mean
    ys = ys * val_set.std + val_set.mean

    ## plot the prediction and GT close value
    plt.plot(ys.cpu().numpy(), label='GT')
    plt.plot(preds.cpu().numpy(), label='pred')
    plt.title("[Ep %d] GT vs Pred"%(epoch))
    plt.legend()
    plt.show()

    if writer is not None:
        writer.add_scalar('EpLoss/val', ep_loss, epoch)
    return ep_loss

def train_main(net, train_set, val_set, loss_fn, batch_size, lr, n_epoch, name='net'):
    train_loader = data.DataLoader(train_set, batch_size=batch_size, shuffle=True)
    val_loader = data.DataLoader(val_set, batch_size=1)

    save_dir = f'drive/MyDrive/COMP4211/{name}_{batch_size}_{lr}_{n_epoch}'
    writer = SummaryWriter(log_dir=osp.join(save_dir, 'log'))
    device = 'cpu' if not torch.cuda.is_available() else 'cuda'
    net = net.to(device)
    optimizer = torch.optim.AdamW(net.parameters(), lr=lr)

    train_ep_losses, val_ep_losses = [], []
    for epoch in range(n_epoch):
        train_loss = train_epoch(net, optimizer, loss_fn, train_loader, epoch, writer, device)
        val_loss = val_epoch(net, loss_fn, val_loader, epoch, val_set, writer, device)
        train_ep_losses.append(train_loss)
        val_ep_losses.append(val_loss)
        if (epoch + 1) % 5 == 0:
            os.makedirs(osp.join(save_dir, 'weights'), exist_ok=True)
            torch.save(net.state_dict(), osp.join(save_dir, 'weights/ep%d.pth' % (epoch + 1)))
    
    plt.plot(torch.tensor(train_ep_losses).cpu().numpy(), label='train')
    plt.plot(torch.tensor(val_ep_losses).cpu().numpy(), label='val')
    plt.xlabel('n_epoch')
    plt.legend()
    plt.show()

In [144]:
train_FC_Net_Dataset = FC_Net_Dataset(split=0)
val_FC_Net_Dataset = FC_Net_Dataset(split=1)
test_FC_Net_Dataset = FC_Net_Dataset(split=2)

fc_net = FC_Net();
loss = nn.L1Loss()